// components/Skills.tsx
'use client'

import { motion } from 'framer-motion'
import { useInView } from 'framer-motion'
import { useRef } from 'react'

const skills = [
  { category: 'Languages', items: ['JavaScript', 'TypeScript', 'HTML5', 'CSS3'] },
  { category: 'Frameworks', items: ['React', 'Angular', 'Next.js', 'Vue.js'] },
  { category: 'Styling', items: ['Tailwind CSS', 'SASS', 'Bootstrap', 'Styled Components'] },
  { category: 'Tools', items: ['Git', 'Webpack', 'Vite', 'Jest', 'ESLint'] },
  { category: 'Backend', items: ['Node.js', 'Express', 'REST APIs', 'GraphQL'] },
  { category: 'Cloud & DevOps', items: ['AWS', 'Azure', 'CI/CD', 'Docker'] },
]

export default function Skills() {
  const ref = useRef(null)
  const isInView = useInView(ref, { once: true, margin: '-100px' })

  return (
    <section id="skills" className="min-h-screen flex items-center py-20 px-6 sm:px-8">
      <div className="max-w-4xl mx-auto w-full">
        <motion.div
          ref={ref}
          initial={{ opacity: 0, y: 50 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
        >
          <motion.h2
            className="text-2xl sm:text-3xl font-bold text-white mb-12 flex items-center justify-center"
            initial={{ opacity: 0, x: -20 }}
            animate={isInView ? { opacity: 1, x: 0 } : {}}
          >
            <span className="text-green font-mono text-lg mr-4">05.</span>
            Skills & Technologies
          </motion.h2>

          <div className="grid md:grid-cols-2 gap-6">
            {skills.map((skillGroup, index) => (
              <motion.div
                key={skillGroup.category}
                className="bg-light-navy rounded-lg p-6"
                initial={{ opacity: 0, y: 30 }}
                animate={isInView ? { opacity: 1, y: 0 } : {}}
                transition={{ delay: index * 0.1 }}
                whileHover={{ y: -5 }}
              >
                <h3 className="text-green font-semibold mb-4">{skillGroup.category}</h3>
                <div className="flex flex-wrap gap-2">
                  {skillGroup.items.map((skill) => (
                    <motion.span
                      key={skill}
                      className="px-3 py-1 bg-navy text-slate rounded text-sm font-mono"
                      whileHover={{ scale: 1.05, backgroundColor: '#64ffda', color: '#0a192f' }}
                      transition={{ duration: 0.2 }}
                    >
                      {skill}
                    </motion.span>
                  ))}
                </div>
              </motion.div>
            ))}
          </div>
        </motion.div>
      </div>
    </section>
  )
}

// src/components/skills/skills.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { trigger, transition, style, animate, query, stagger } from '@angular/animations';

interface SkillGroup {
  category: string;
  items: string[];
}

@Component({
  selector: 'app-skills',
  standalone: true,
  imports: [CommonModule],
  template: `
    <section id="skills" class="min-h-screen flex items-center py-20 px-6 sm:px-8">
      <div class="max-w-4xl mx-auto w-full">
        <div [@fadeInUp]="'in'">
          <h2 
            class="text-2xl sm:text-3xl font-bold text-white mb-12 flex items-center justify-center"
            [@slideInLeft]="'in'">
            <span class="text-green font-mono text-lg mr-4">05.</span>
            Skills & Technologies
          </h2>

          <div 
            class="grid md:grid-cols-2 gap-6"
            [@gridAnimation]="'in'">
            <div 
              *ngFor="let skillGroup of skills; let i = index"
              class="bg-light-navy rounded-lg p-6 hover:scale-105 transition-transform"
              [@skillCardAnimation]="'in'"
              [style.animation-delay.ms]="i * 100">
              <h3 class="text-green font-semibold mb-4">{{ skillGroup.category }}</h3>
              <div class="flex flex-wrap gap-2" [@tagsAnimation]="'in'">
                <span 
                  *ngFor="let skill of skillGroup.items"
                  class="px-3 py-1 bg-navy text-slate rounded text-sm font-mono hover:bg-green hover:text-navy transition-colors cursor-pointer"
                  [@tagAnimation]="'in'">
                  {{ skill }}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  `,
  animations: [
    trigger('fadeInUp', [
      transition(':enter', [
        style({ opacity: 0, transform: 'translateY(50px)' }),
        animate('600ms ease-out', style({ opacity: 1, transform: 'translateY(0)' }))
      ])
    ]),
    trigger('slideInLeft', [
      transition(':enter', [
        style({ opacity: 0, transform: 'translateX(-20px)' }),
        animate('500ms ease-out', style({ opacity: 1, transform: 'translateX(0)' }))
      ])
    ]),
    trigger('gridAnimation', [
      transition(':enter', [
        query('div', [
          stagger(100, [
            style({ opacity: 0, transform: 'translateY(30px)' }),
            animate('500ms ease-out', style({ opacity: 1, transform: 'translateY(0)' }))
          ])
        ])
      ])
    ]),
    trigger('skillCardAnimation', [
      transition(':enter', [
        style({ opacity: 0, transform: 'translateY(30px)' }),
        animate('500ms ease-out', style({ opacity: 1, transform: 'translateY(0)' }))
      ])
    ]),
    trigger('tagsAnimation', [
      transition(':enter', [
        query('span', [
          stagger(50, [
            style({ opacity: 0, transform: 'scale(0.8)' }),
            animate('300ms ease-out', style({ opacity: 1, transform: 'scale(1)' }))
          ])
        ])
      ])
    ]),
    trigger('tagAnimation', [
      transition(':enter', [
        style({ opacity: 0, transform: 'scale(0.8)' }),
        animate('300ms ease-out', style({ opacity: 1, transform: 'scale(1)' }))
      ])
    ])
  ]
})
export class SkillsComponent {
  skills: SkillGroup[] = [
    { category: 'Languages', items: ['JavaScript', 'TypeScript', 'HTML5', 'CSS3'] },
    { category: 'Frameworks', items: ['React', 'Angular', 'Next.js', 'Vue.js'] },
    { category: 'Styling', items: ['Tailwind CSS', 'SASS', 'Bootstrap', 'Styled Components'] },
    { category: 'Tools', items: ['Git', 'Webpack', 'Vite', 'Jest', 'ESLint'] },
    { category: 'Backend', items: ['Node.js', 'Express', 'REST APIs', 'GraphQL'] },
    { category: 'Cloud & DevOps', items: ['AWS', 'Azure', 'CI/CD', 'Docker'] },
  ];
}
